apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortio-client
  namespace: fortio-istio-default
---
apiVersion: v1
kind: Service
metadata:
  name: fortio-client
  namespace: fortio-istio-default
spec:
  selector:
    app: fortio-client
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fortio-istio-default
  labels:
    app: fortio-client
  name: fortio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio-client
  template:
    metadata:
      namespace: fortio-istio-default
      labels:
        app: fortio-client
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest_release
        env:       
        ports:
        - containerPort: 8080
          name: http-fortio
        - containerPort: 8079
          name: grpc-ping        
        volumeMounts:
        - name: reports
          mountPath: /var/lib/fortio
      volumes:
      - name: reports
        emptyDir:
            medium: Memory
      serviceAccountName: fortio-client
      nodeSelector:
        nodegroup: services