{
 "title": "Envoy Utilization",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "envoy_listener_http_fortio_server_defaults_default_default_dc1_downstream_rq_completed",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_listener_http_fortio_server_defaults_default_default_dc1_downstream_rq_xx{app=\"fortio-client\", envoy_response_code_class=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_listener_http_downstream_rq_xx{pod=\"fortio-server-defaults-ff55bff89-qrbst\", envoy_response_code_class=\"1\", envoy_listener_address=\"0.0.0.0_20200\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "envoy_listener_http_downstream_rq_completed{pod=\"fortio-server-defaults-ff55bff89-qrbst\", envoy_listener_address=\"0.0.0.0_20200\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Utilization Consul dataplane container - Defaults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"consul-dataplane\", pod=~\"fortio-server-defaults.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-defaults.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-defaults.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "Dataplane Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{pod=~\"fortio-server-defaults.*\", container=\"consul-dataplane\"}",
     "legendFormat": "Memory Max Usage {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=~\"fortio-server.*\", container=\"envoy-sidecar\"}",
     "legendFormat": "Memory Limit {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", pod=~\"fortio-client.*\", container=\"envoy-sidecar\"}",
     "legendFormat": "Memory Request {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Consul dataplane container - small",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"consul-dataplane\", pod=~\"fortio-server-small.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-small.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-small.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - defaults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{container=\"consul-dataplane\", pod=\"fortio-server-defaults.*\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "CPU Utilization Consul dataplane container - medium",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"consul-dataplane\", pod=~\"fortio-server-medium.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-medium.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-medium.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - small",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"fortio-server-small.*\", container=\"consul-dataplane\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "CPU Utilization Consul dataplane container - large",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"consul-dataplane\", pod=~\"fortio-server-large.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-large.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-large.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - medium",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"fortio-server-medium.*\", container=\"consul-dataplane\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "Network Bytes Rx and Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"fortio-server-defaults.*\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"fortio-server-defaults-.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - large",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"fortio-server-large.*\", container=\"consul-dataplane\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_cx_total{pod=~\"fortio-server.*|fortio-server-defaults-ff55bff89-qrbst\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}