{
 "title": "Envoy Utilization",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization Consul dataplane container - Defaults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"envoy-sidecar\", pod=~\"fortio-server-defaults.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-defaults.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-defaults.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - defaults",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"fortio-server-defaults.*\", container=\"envoy-sidecar\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "CPU Utilization Consul dataplane container - small",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"envoy-sidecar\", pod=~\"fortio-server-small.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-small.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-small.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - small",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"fortio-server-small.*\", container=\"envoy-sidecar\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "CPU Utilization Consul dataplane container - medium",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"envoy-sidecar\", pod=~\"fortio-server-medium.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-medium.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-medium.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - medium",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"fortio-server-medium.*\", container=\"envoy-sidecar\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "CPU Utilization Consul dataplane container - large",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"envoy-sidecar\", pod=~\"fortio-server-large.*\"}[5m])",
     "legendFormat": "CPU Usage "
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"fortio-server-large.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Limit"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"fortio-server-large.*\", resource=\"cpu\", container=\"envoy-sidecar\"}",
     "legendFormat": "CPU Resource Request"
    }
   ]
  },
  {
   "title": "CPU Throttled Seconds - large",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"fortio-server-large.*\", container=\"envoy-sidecar\"}[5m])",
     "legendFormat": "CPU Throttled Seconds"
    }
   ]
  },
  {
   "title": "Envoy Proxy Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{pod=~\"fortio-server-.*\", container=\"envoy-sidecar\"}",
     "legendFormat": "Memory Max Usage {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=~\"fortio-server.*\", container=\"envoy-sidecar\"}",
     "legendFormat": "Memory Limit {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{resource=\"memory\", pod=~\"fortio-client.*\", container=\"envoy-sidecar\"}",
     "legendFormat": "Memory Request {{pod}}"
    }
   ]
  },
  {
   "title": "Upstream Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_cx_total{pod=~\"fortio-server.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Bytes Rx and Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"fortio-server.*\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"fortio-server.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}