{
 "title": "Consul K8s monitoring 2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Consul Servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "consul_consul_server_0_members_servers{pod=\"consul-server-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Leader (1: Healthy)",
   "type": "timeseries",
   "description": "Must be 1",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum({__name__=~\".+server_isLeader\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Raft Leader LastContact (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "consul_raft_leader_lastContact{quantile=\"0.9\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Follower Append Entries Latency (in millisecond)",
   "type": "timeseries",
   "description": "Use consul.raft.rpc.appendEntries to understand how long it takes a follower node to process newly received Raft logs from the leader. Like consul.raft.commitTime, increases in this metric can indicate higher load on your Consul servers, and come with a risk of stale data. Since this metric is exposed within each follower, you should aggregate it as both an average (to track overall load on your Raft servers) and a percentile (to watch for outlier nodes).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "consul_raft_rpc_appendEntries{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "consul_raft_rpc_appendEntries{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Leader Raft Commit Latency (in millisecond)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "consul_raft_commitTime{quantile=\"0.99\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "consul_raft_commitTime{quantile=\"0.5\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Utilization (Consul Servers)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "CPU Usage in Seconds (Consul servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"consul\", pod=~\"consul-server-.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit in Seconds (Consul Servers)",
   "type": "gauge",
   "description": "All consul servers have the same limit",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"cpu\", pod=\"consul-server-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (Consul servers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"consul\", pod=~\"consul-server-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit (Consul Servers)",
   "type": "gauge",
   "description": "All consul servers have the same limit",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{resource=\"memory\", pod=\"consul-server-0\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}