apiVersion: v1
kind: ServiceAccount
metadata:
  name:   fortio-server-defaults
  namespace: fortio-istio-tcp
---
apiVersion: v1
kind: Service
metadata:
  name:   fortio-server-defaults
  namespace: fortio-istio-tcp
spec:
  selector:
    app:   fortio-server-defaults
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: grpc
    port: 8079
    targetPort: 8079
  - name: tcp
    port: 8078
    targetPort: 8078
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fortio-istio-tcp
  labels:
    app:   fortio-server-defaults
  name:   fortio-server-defaults
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   fortio-server-defaults
  template:
    metadata:
      namespace: fortio-istio-tcp
      labels:
        app:   fortio-server-defaults
    spec:
      containers:
      - name:   fortio-server-defaults
        image: fortio/fortio:latest_release
        env:
        ports:
        - containerPort: 8080
          name: http-echo
        - containerPort: 8079
          name: grpc-ping
        - containerPort: 8078
          name: tcp-echo
      serviceAccountName:   fortio-server-defaults
      nodeSelector:
        nodegroup: services