apiVersion: v1
kind: ServiceAccount
metadata:
  name:   fortio-server-defaults-grpc
  namespace: fortio-istio-tcp
---
apiVersion: v1
kind: Service
metadata:
  name:   fortio-server-defaults-grpc
  namespace: fortio-istio-tcp
spec:
  selector:
    app:   fortio-server-defaults-grpc
  ports:
  - port: 8079
    targetPort: 8079
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fortio-istio-tcp
  labels:
    app:   fortio-server-defaults-grpc
  name:   fortio-server-defaults-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   fortio-server-defaults-grpc
  template:
    metadata:
      namespace: fortio-istio-tcp
      labels:
        app:   fortio-server-defaults-grpc
    spec:
      containers:
      - name:   fortio-server-defaults-grpc
        image: fortio/fortio:latest_release
        env:       
        ports:
        - containerPort: 8080
          name: http-echo
        - containerPort: 8079
          name: grpc-ping
        - containerPort: 8078
          name: tcp-echo
      serviceAccountName:   fortio-server-defaults-grpc
      nodeSelector:
        nodegroup: services