---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api
spec:
  destination:
    name: api
  sources:
  - name: web
    action: allow
  - name: web
    namespace: default
    peer: dc1-default
    action: allow